### ISSUE TITLE
read packet from back-end (individual)

### ISSUE THREAD

**Issue by Phillipnewell** [cs481-ekh/f22-gneiss#177]
As a user, I want to be able to get an individual packet pdf from the back end, so I can examine it in the front end

## Definition of Done
- [x] Packets are selected correctly based on their packetID
- [x] Users with 'user' role are only able to access packets they have created themselves
- [x] Packet PDFs are passed in the response body and able to be viewed

## Tasks
- [x] #205
- [x] #206 
- [ ] #207

**Comment by TheodoreRamey** [comment]
Unable to finish in sprint 3 due the the same issues as #178, as this story also requires both controllers have access to the same component, meaning DI through Spring Boot needs to be implemented.

**Comment by TheodoreRamey** [comment]
Spent ~4 hours working on this. Figured out the correct way to turn a file into a byte array, found out how to reference files that exist in the docker volume, tried several different ways to return the byte array via http response, added unit tests, and tested it all via postman.
